my_dbt_project:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-thrift  # Service name of thrift server in docker-compose.yaml
      port: 10000 # Thrift server port
      schema: default
      user: hive
      connect_retries: 5
      spark.hadoop.fs.s3a.endpoint: http://minio:9000
      spark.hadoop.fs.s3a.access.key: minioadmin
      spark.hadoop.fs.s3a.secret.key: minioadmin
      spark.hadoop.fs.s3a.path.style.access: true # Enable path style access for MinIO
